import torch
# Suppose 1000 images, shape generated by Vision encoder is probably around [b, seq_len, dim]
# the vision block outputs a long sequence.
# But let's check the size of the tensor from test_qwen3 output: pixel_values was [256, 1536]
# Does vision.blocks.26 output [1, 256, 1536] per image?
# If so, 1000 images * 256 * 1536 * 4 bytes (float32) = 1000 * 256 * 1536 * 4 bytes
size = 1000 * 256 * 1536 * 4 / (1024**3)
print(f"Memory footprint of train features if float32: {size:.2f} GB")
